version: 0.2

phases:
  install:
    commands:
      - npm install -g
  pre_build:
    commands:
      - npm install rdvue -g
      - npm install buefy --force
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo This is the end of Build
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
