describe('Login Process', () => {
  it('Enter Correct Login Information', () => {
    cy.visit('localhost:8080')
    cy.get('#username').type('bryan')
    cy.get('#username').should('have.value', 'bryan')
    cy.get('#password').type('test')
    cy.get('#password').should('have.value', 'test')
    cy.get('#validateButton').click()
    cy.url().should('include', '/home?')
  })
  it('Enter Incorrert Login Information', () => {
    const alertShown = cy.stub().as("alertShown")
    cy.visit('localhost:8080')
    cy.get('#username').type('anything')
    cy.get('#username').should('have.value', 'anything')
    cy.get('#password').type('something')
    cy.get('#password').should('have.value', 'something')
    cy.get('#validateButton').click()
    cy.on('window:alert', alertShown)
    cy.get("@alertShown").should('have.been.calledOnceWith', 'Login details are incorrect. Please enter correct username or password to continue')
  })
  it('No text was entered into either username or password', () => {
    const alertShown = cy.stub().as("alertShown")
    cy.visit('localhost:8080')
    cy.get('#validateButton').click()
    cy.on('window:alert', alertShown)
    cy.get('@alertShown').should('have.been.calledOnceWith', 'Name and Password must be filled')
  })
})