version: "3.5"

services:
  iac-base:
    container_name: iac-goose-social
    build: 
      context: .
    image: realdecoy/iac-base:rdvue
    working_dir: /app
    env_file:
     - ./prod.env
    # - ./test.env
    #  - ./personal.env
    volumes:
     - "./meta/.ssh:/root/.ssh"
     - "./meta/.aws:/root/.aws"
     - '../:/app'
    tty: true
